### ISSUE TITLE
Tag Non-English Style Guides

### ISSUE THREAD

**Issue by stevendaniels** [xiaobeicn/Style-Guide-Collection#5]
Style guides in languages other than english should be tagged with that language.

e.g.
- Javascript
  - [adamlu/javascript-style-guide](https://github.com/adamlu/javascript-style-guide)

Should be
- Javascript
  - [adamlu/javascript-style-guide](https://github.com/adamlu/javascript-style-guide) [Chinese]

**Comment by xiaobeicn** [comment]
@stevendaniels  Thanks,good idea

**Comment by xiaobeicn** [comment]
26bc04ed44961b6271f56568a67f8414f1877fdb
